services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.development
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URL=${MONGO_URL}
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - server_node_modules:/app/node_modules

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo-data:
  client_node_modules:
  server_node_modules:
