services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    restart: always
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.production
    environment:
      NODE_ENV: production
      MONGO_URL: ${MONGO_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
